My fork
danchris/eortologio-gnome-shell-extension pull request #2
Opened 2022-08-10 17:37 UTC by rizitis

2022-08-10 17:41 UTC, rizitis commented
Πρόσθεσα κάποιες εορτές που λοίπουν και έβαλα κάποιες στις σωστές ημερομηνίες καθώς υπάρχουν άγιοι από διαφορετικό φύλλο και προτιμούνται σύμφωνα με τον ορθόδοξο συναξαριστή. :)

2022-09-01 18:30 UTC, danchris requested changes
Please resolve the json syntax errors.

2022-09-01 18:30 UTC, danchris commented on eortologio@danchris.github.io/recurring_namedays.json
> +          "Αγγελής"
Please place a comma between array values

2022-09-01 18:30 UTC, danchris commented on eortologio@danchris.github.io/relative_to_easter.json
> +        "Ρόδω",
Please remove trailing comma

2023-07-19 16:40 UTC, closed without merging